version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-nginx
    container_name: laravel-container
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - laravel_network

  db:
    image: mysql:latest
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_laravel_db_name
      MYSQL_USER: your_laravel_db_user
      MYSQL_PASSWORD: your_laravel_db_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  mysql_data:
