version: '3'

networks:
  laravel:

services: 
  server:
    image: 'nginx:stable-alpine'
    container_name: laravel_nginx
    ports: 
      - '8081:80'
    volumes: 
      - "./:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    ports:
      - "3307:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: unless-stopped
    tty: true
    environment:
      - DB_DATABASE=mydb
      - DB_USERNAME=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - laravel

  php: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www/html"
    networks:
      - laravel

networks:
  laravel:

   



